# Generated by Django 4.0.4 on 2022-04-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='job',
            name='application_url',
            field=models.URLField(default='https://www.facebook.com'),
            preserve_default=False,
        ),
    ]
