# Generated by Django 4.0.4 on 2022-04-24 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_company_options_job_application_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='address',
            new_name='country',
        ),
    ]
