# Generated by Django 4.0.4 on 2022-04-30 01:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_address_company_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(upload_to=core.models.upload_image_to),
        ),
    ]
